// Generated by ts-to-zod
import { z } from "zod";

const userIdSchema = z.any();

export const sodaIntakeEntriesSchema = z.object({
  id: z.string(),
  user_id: userIdSchema,
  entry_date: z.date(),
  soda_ml: z.number(),
  container_id: z.number().nullable(),
  container_name: z.string().nullable(),
  source: z.string(),
  created_at: z.date(),
  created_by_user_id: userIdSchema.nullable(),
  logged_at: z.date(),
});

export const sodaIntakeEntriesInitializerSchema = z.object({
  id: z.string().optional(),
  user_id: userIdSchema,
  entry_date: z.date().optional(),
  soda_ml: z.number(),
  container_id: z.number().optional().nullable(),
  container_name: z.string().optional().nullable(),
  source: z.string().optional(),
  created_at: z.date().optional(),
  created_by_user_id: userIdSchema.optional().nullable(),
  logged_at: z.date().optional(),
});

export const sodaIntakeEntriesMutatorSchema = z.object({
  id: z.string().optional(),
  user_id: userIdSchema.optional(),
  entry_date: z.date().optional(),
  soda_ml: z.number().optional(),
  container_id: z.number().optional().nullable(),
  container_name: z.string().optional().nullable(),
  source: z.string().optional(),
  created_at: z.date().optional(),
  created_by_user_id: userIdSchema.optional().nullable(),
  logged_at: z.date().optional(),
});

export type SodaIntakeEntries = z.infer<typeof sodaIntakeEntriesSchema>;
export type SodaIntakeEntriesInitializer = z.infer<typeof sodaIntakeEntriesInitializerSchema>;
export type SodaIntakeEntriesMutator = z.infer<typeof sodaIntakeEntriesMutatorSchema>;
