// Generated by ts-to-zod
import { z } from "zod";

export const userSodaContainersIdSchema = z.number().and(
  z.object({
    __brand: z.literal("public.user_soda_containers"),
  }),
);

const userIdSchema = z.any();

export const userSodaContainersSchema = z.object({
  id: userSodaContainersIdSchema,
  user_id: userIdSchema,
  name: z.string(),
  volume: z.number(),
  unit: z.string(),
  is_primary: z.boolean().nullable(),
  created_at: z.date(),
  updated_at: z.date(),
  servings_per_container: z.number(),
});

export const userSodaContainersInitializerSchema = z.object({
  id: userSodaContainersIdSchema.optional(),
  user_id: userIdSchema,
  name: z.string(),
  volume: z.number(),
  unit: z.string(),
  is_primary: z.boolean().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  servings_per_container: z.number().optional(),
});

export const userSodaContainersMutatorSchema = z.object({
  id: userSodaContainersIdSchema.optional(),
  user_id: userIdSchema.optional(),
  name: z.string().optional(),
  volume: z.number().optional(),
  unit: z.string().optional(),
  is_primary: z.boolean().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  servings_per_container: z.number().optional(),
});

export type UserSodaContainers = z.infer<typeof userSodaContainersSchema>;
export type UserSodaContainersInitializer = z.infer<typeof userSodaContainersInitializerSchema>;
export type UserSodaContainersMutator = z.infer<typeof userSodaContainersMutatorSchema>;
