// Generated by ts-to-zod (Extended for progression engine)
import { z } from "zod";

export const workoutPresetExercisesIdSchema = z.number().and(
  z.object({
    __brand: z.literal("public.workout_preset_exercises"),
  }),
);

const workoutPresetsIdSchema = z.any();
const exercisesIdSchema = z.any();

export const workoutPresetExercisesSchema = z.object({
  id: workoutPresetExercisesIdSchema,
  workout_preset_id: workoutPresetsIdSchema,
  exercise_id: exercisesIdSchema,
  image_url: z.string().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  sort_order: z.number().nullable(),
  superset_group: z.number().nullable(),
  // Progression & Equipment Fields
  progression_mode: z.enum(["rep_goal", "fixed", "step_load", "manual"]).nullable().optional(),
  rep_goal: z.number().int().nullable().optional(),
  increment_type: z.enum(["weight", "reps"]).nullable().optional(),
  increment_value: z.number().nullable().optional(),
  equipment_brand: z.string().nullable().optional(),
  // Manually added (file is ts-to-zod generated; precedent:
  // UserWaterContainers.zod.ts). Keep on regen. Within-session ramp, kg.
  ramp_increment: z.number().nullable().optional(),
});

export const workoutPresetExercisesInitializerSchema = z.object({
  id: workoutPresetExercisesIdSchema.optional(),
  workout_preset_id: workoutPresetsIdSchema,
  exercise_id: exercisesIdSchema,
  image_url: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  sort_order: z.number().optional().nullable(),
  superset_group: z.number().optional().nullable(),
  // Progression & Equipment Fields
  progression_mode: z.enum(["rep_goal", "fixed", "step_load", "manual"]).optional().nullable(),
  rep_goal: z.number().int().optional().nullable(),
  increment_type: z.enum(["weight", "reps"]).optional().nullable(),
  increment_value: z.number().optional().nullable(),
  equipment_brand: z.string().optional().nullable(),
  // Manually added (file is ts-to-zod generated; precedent:
  // UserWaterContainers.zod.ts). Keep on regen. Within-session ramp, kg.
  ramp_increment: z.number().optional().nullable(),
});

export const workoutPresetExercisesMutatorSchema = z.object({
  id: workoutPresetExercisesIdSchema.optional(),
  workout_preset_id: workoutPresetsIdSchema.optional(),
  exercise_id: exercisesIdSchema.optional(),
  image_url: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  sort_order: z.number().optional().nullable(),
  superset_group: z.number().optional().nullable(),
  // Progression & Equipment Fields
  progression_mode: z.enum(["rep_goal", "fixed", "step_load", "manual"]).optional().nullable(),
  rep_goal: z.number().int().optional().nullable(),
  increment_type: z.enum(["weight", "reps"]).optional().nullable(),
  increment_value: z.number().optional().nullable(),
  equipment_brand: z.string().optional().nullable(),
  // Manually added (file is ts-to-zod generated; precedent:
  // UserWaterContainers.zod.ts). Keep on regen. Within-session ramp, kg.
  ramp_increment: z.number().optional().nullable(),
});

export type WorkoutPresetExercises = z.infer<
  typeof workoutPresetExercisesSchema
>;
export type WorkoutPresetExercisesInitializer = z.infer<
  typeof workoutPresetExercisesInitializerSchema
>;
export type WorkoutPresetExercisesMutator = z.infer<
  typeof workoutPresetExercisesMutatorSchema
>;