// Generated by ts-to-zod
import { z } from "zod";

export const workoutPlanTemplatesIdSchema = z.number().and(
  z.object({
    __brand: z.literal("public.workout_plan_templates"),
  }),
);

const userIdSchema = z.any();

export const workoutPlanTemplatesSchema = z.object({
  id: workoutPlanTemplatesIdSchema,
  user_id: userIdSchema,
  plan_name: z.string(),
  description: z.string().nullable(),
  start_date: z.date().nullable(),
  end_date: z.date().nullable(),
  is_active: z.boolean().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  // Manually added (file is ts-to-zod generated; precedent: UserWaterContainers.zod.ts).
  // Keep on regen. #1836: sequential workout plan mode & entry mode.
  schedule_type: z.enum(["weekly", "sequential"]),
  entry_mode: z.enum(["prompt", "prefill"]),
});

export const workoutPlanTemplatesInitializerSchema = z.object({
  id: workoutPlanTemplatesIdSchema.optional(),
  user_id: userIdSchema,
  plan_name: z.string(),
  description: z.string().optional().nullable(),
  start_date: z.date().optional().nullable(),
  end_date: z.date().optional().nullable(),
  is_active: z.boolean().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  schedule_type: z.enum(["weekly", "sequential"]).optional(),
  entry_mode: z.enum(["prompt", "prefill"]).optional(),
});

export const workoutPlanTemplatesMutatorSchema = z.object({
  id: workoutPlanTemplatesIdSchema.optional(),
  user_id: userIdSchema.optional(),
  plan_name: z.string().optional(),
  description: z.string().optional().nullable(),
  start_date: z.date().optional().nullable(),
  end_date: z.date().optional().nullable(),
  is_active: z.boolean().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  schedule_type: z.enum(["weekly", "sequential"]).optional(),
  entry_mode: z.enum(["prompt", "prefill"]).optional(),
});

export type WorkoutPlanTemplates = z.infer<typeof workoutPlanTemplatesSchema>;
export type WorkoutPlanTemplatesInitializer = z.infer<
  typeof workoutPlanTemplatesInitializerSchema
>;
export type WorkoutPlanTemplatesMutator = z.infer<
  typeof workoutPlanTemplatesMutatorSchema
>;
